using System;
using System.Linq;
using System.Text;
using System.Globalization;
using System.Collections.Generic;

namespace LibSciyonVFD
{
    public partial class VFDConfiguration
    {
		#region P0组 别名
		public ConfigItem P0_00 => RatedPower;
		public ConfigItem P0_01 => RatedCurrent;
		public ConfigItem P0_02 => RatedVoltage;
		public ConfigItem P0_03 => LoadType;
		public ConfigItem P0_04 => FuncDisplayCtrl;
		public ConfigItem P0_05 => FuncInit;
		public ConfigItem P0_06 => ControlMode;
		public ConfigItem P0_07 => CmdSource;
		public ConfigItem P0_08 => MotorDirection;
		public ConfigItem P0_09 => MaxFreq;
		public ConfigItem P0_10 => ReservedP010;
		public ConfigItem P0_11 => FreqUpper;
		public ConfigItem P0_12 => FreqLower;
		public ConfigItem P0_13 => MainFreqSrc;
		public ConfigItem P0_14 => SubFreqSrc;
		public ConfigItem P0_15 => MainSubRelation;
		public ConfigItem P0_16 => PresetFreq;
		public ConfigItem P0_17 => SubFreqRef;
		public ConfigItem P0_18 => SubFreqGain;
		public ConfigItem P0_19 => FreqBiasCfg;
		public ConfigItem P0_20 => FreqBiasRate;
		public ConfigItem P0_21 => AccTime0;
		public ConfigItem P0_22 => DecTime0;
		public ConfigItem P0_23 => MotorParamGroup;
		public ConfigItem P0_24 => TuneMode;
		public ConfigItem P0_25 => JogPriority;
		public ConfigItem P0_26 => FreqAccuracy;
		public ConfigItem P0_27 => IndustryMacro;
		public ConfigItem P0_28 => ExtCardCfg;
		#endregion
		#region P1组 别名
		public ConfigItem P1_00 => Motor1Type;
		public ConfigItem P1_01 => Motor1RatedPower;
		public ConfigItem P1_02 => Motor1RatedVoltage;
		public ConfigItem P1_03 => Motor1RatedCurrent;
		public ConfigItem P1_04 => Motor1RatedFreq;
		public ConfigItem P1_05 => Motor1RatedSpeed;
		public ConfigItem P1_06 => Motor1PoleCount;
		public ConfigItem P1_07 => Motor1StatorRes;
		public ConfigItem P1_08 => Motor1RotorRes;
		public ConfigItem P1_09 => Motor1LeakInduct;
		public ConfigItem P1_10 => Motor1MutualInduct;
		public ConfigItem P1_11 => Motor1NoLoadCurrent;
		public ConfigItem P1_12 => Motor1BackEMF;
		public ConfigItem P1_13 => Motor1InitPos;
		public ConfigItem P1_14 => Motor1CarrierFreq;
		public ConfigItem P1_15 => CarrierOptimize;
		#endregion
		#region P2组 别名
		public ConfigItem P2_00 => VfCurve;
		public ConfigItem P2_01 => VfFreqPoint1;
		public ConfigItem P2_02 => VfVoltPoint1;
		public ConfigItem P2_03 => VfFreqPoint2;
		public ConfigItem P2_04 => VfVoltPoint2;
		public ConfigItem P2_05 => VfFreqPoint3;
		public ConfigItem P2_06 => VfVoltPoint3;
		public ConfigItem P2_07 => VfSepVoltSrc;
		public ConfigItem P2_08 => VfSepVoltDigital;
		public ConfigItem P2_09 => VfSepAccTime;
		public ConfigItem P2_10 => VfSepDecTime;
		public ConfigItem P2_11 => TorqueBoost;
		public ConfigItem P2_12 => TorqueBoostFilter;
		public ConfigItem P2_13 => TorqueBoostCutFreq;
		public ConfigItem P2_14 => SlipCompGain;
		public ConfigItem P2_15 => SlipCompFilter;
		public ConfigItem P2_16 => CurrentOscSuppress;
		public ConfigItem P2_17 => MotoringCurrentLimit;
		public ConfigItem P2_18 => BrakingCurrentLimit;
		public ConfigItem P2_19 => AVRMode;
		public ConfigItem P2_20 => DroopFreq;
		#endregion
		#region P3组 别名
		public ConfigItem P3_00 => LowSpeedASR_P;
		public ConfigItem P3_01 => LowSpeedASR_I;
		public ConfigItem P3_02 => LowSpeedASR_SwitchFreq;
		public ConfigItem P3_03 => HighSpeedASR_P;
		public ConfigItem P3_04 => HighSpeedASR_I;
		public ConfigItem P3_05 => HighSpeedASR_SwitchFreq;
		public ConfigItem P3_06 => FluxReg_P;
		public ConfigItem P3_07 => FluxReg_I;
		public ConfigItem P3_08 => TorqueReg_P;
		public ConfigItem P3_09 => TorqueReg_I;
		public ConfigItem P3_10 => MotoringTorqueLimitSrc;
		public ConfigItem P3_11 => MotoringTorqueLimit;
		public ConfigItem P3_12 => BrakingTorqueLimit;
		public ConfigItem P3_13 => VectorSlipCompGain;
		public ConfigItem P3_14 => InertiaCompGain;
		public ConfigItem P3_15 => TorqueCmdSrc;
		public ConfigItem P3_16 => TorqueCmdDigital;
		public ConfigItem P3_17 => TorqueCmdFilter;
		public ConfigItem P3_18 => SpeedLimitSrc;
		public ConfigItem P3_19 => SpeedLimitDigital;
		#endregion
		#region P4组 别名
		public ConfigItem P4_00 => StartMode;
		public ConfigItem P4_01 => StartFreq;
		public ConfigItem P4_02 => StartFreqHoldTime;
		public ConfigItem P4_03 => StartFreqDirection;
		public ConfigItem P4_04 => StartBrakeCurrent;
		public ConfigItem P4_05 => StartBrakeHoldTime;
		public ConfigItem P4_06 => StartTrackCurrent;
		public ConfigItem P4_07 => StartTrackTime;
		public ConfigItem P4_08 => StopMode;
		public ConfigItem P4_09 => StopBrakeFreq;
		public ConfigItem P4_10 => StopBrakeCurrent;
		public ConfigItem P4_11 => StopBrakeHoldTime;
		public ConfigItem P4_12 => ReverseDeadTime;
		public ConfigItem P4_13 => ZeroHzVoltageMode;
		#endregion
		#region P5组 别名
		public ConfigItem P5_00 => AccDecTimeUnit;
		public ConfigItem P5_01 => AccDecMode;
		public ConfigItem P5_02 => AccTime1;
		public ConfigItem P5_03 => DecTime1;
		public ConfigItem P5_04 => AccTime2;
		public ConfigItem P5_05 => DecTime2;
		public ConfigItem P5_06 => AccTime3;
		public ConfigItem P5_07 => DecTime3;
		public ConfigItem P5_08 => AccTurnFreq1;
		public ConfigItem P5_09 => AccTurnFreq2;
		public ConfigItem P5_10 => AccTurnFreq3;
		public ConfigItem P5_11 => DecTurnFreq1;
		public ConfigItem P5_12 => DecTurnFreq2;
		public ConfigItem P5_13 => DecTurnFreq3;
		public ConfigItem P5_14 => JogFreq;
		public ConfigItem P5_15 => JogAccTime;
		public ConfigItem P5_16 => JogDecTime;
		public ConfigItem P5_17 => JumpFreq1_Upper;
		public ConfigItem P5_18 => JumpFreq1_Lower;
		public ConfigItem P5_19 => JumpFreq2_Upper;
		public ConfigItem P5_20 => JumpFreq2_Lower;
		public ConfigItem P5_21 => JumpFreq3_Upper;
		public ConfigItem P5_22 => JumpFreq3_Lower;
		#endregion
		#region P6组 别名
		public ConfigItem P6_00 => TerminalConfig;
		public ConfigItem P6_01 => X1Function;
		public ConfigItem P6_02 => X2Function;
		public ConfigItem P6_03 => X3Function;
		public ConfigItem P6_04 => X4Function;
		public ConfigItem P6_05 => X5Function;
		public ConfigItem P6_06 => X6Function;
		public ConfigItem P6_07 => AI1Function;
		public ConfigItem P6_08 => AI2Function;
		public ConfigItem P6_09 => InputLevel1;
		public ConfigItem P6_10 => InputLevel2;
		public ConfigItem P6_11 => TerminalFilterTime;
		public ConfigItem P6_12 => X1Delay;
		public ConfigItem P6_13 => X2Delay;
		public ConfigItem P6_14 => AI1Gain;
		public ConfigItem P6_15 => AI1Offset;
		public ConfigItem P6_16 => AI1Filter;
		public ConfigItem P6_17 => AI1CurveSelect;
		public ConfigItem P6_18 => AI1Point1;
		public ConfigItem P6_19 => AI1Point1Set;
		public ConfigItem P6_20 => AI1Point2;
		public ConfigItem P6_21 => AI1Point2Set;
		public ConfigItem P6_22 => AI2Gain;
		public ConfigItem P6_23 => AI2Offset;
		public ConfigItem P6_24 => AI2Filter;
		public ConfigItem P6_25 => AI2CurveSelect;
		public ConfigItem P6_26 => AI2Point1;
		public ConfigItem P6_27 => AI2Point1Set;
		public ConfigItem P6_28 => AI2Point2;
		public ConfigItem P6_29 => AI2Point2Set;
		public ConfigItem P6_30 => PFIFilter;
		public ConfigItem P6_31 => PFILow;
		public ConfigItem P6_32 => PFILowSet;
		public ConfigItem P6_33 => PFIHigh;
		public ConfigItem P6_34 => PFIHighSet;
		#endregion
		#region P7组 别名
		public ConfigItem P7_00 => PFOEnable;
		public ConfigItem P7_01 => Y1Function;
		public ConfigItem P7_02 => Y2Function;
		public ConfigItem P7_03 => RFunction;
		public ConfigItem P7_04 => OutputLevel;
		public ConfigItem P7_05 => Y1Delay;
		public ConfigItem P7_06 => Y2Delay;
		public ConfigItem P7_07 => RDelay;
		public ConfigItem P7_08 => AO1Function;
		public ConfigItem P7_09 => AO1Gain;
		public ConfigItem P7_10 => AO1Offset;
		public ConfigItem P7_11 => AO1Filter;
		public ConfigItem P7_12 => PFOFunction;
		public ConfigItem P7_13 => PFOFilter;
		public ConfigItem P7_14 => PFOLow;
		public ConfigItem P7_15 => PFOLowSet;
		public ConfigItem P7_16 => PFOHigh;
		public ConfigItem P7_17 => PFOHighSet;
		#endregion
		#region P8组 别名
		public ConfigItem P8_00 => MultiStep0;
		public ConfigItem P8_01 => MultiStep1;
		public ConfigItem P8_02 => MultiStep2;
		public ConfigItem P8_03 => MultiStep3;
		public ConfigItem P8_04 => MultiStep4;
		public ConfigItem P8_05 => MultiStep5;
		public ConfigItem P8_06 => MultiStep6;
		public ConfigItem P8_07 => MultiStep7;
		public ConfigItem P8_08 => MultiStep8;
		public ConfigItem P8_09 => MultiStep9;
		public ConfigItem P8_10 => MultiStep10;
		public ConfigItem P8_11 => MultiStep11;
		public ConfigItem P8_12 => MultiStep12;
		public ConfigItem P8_13 => MultiStep13;
		public ConfigItem P8_14 => MultiStep14;
		public ConfigItem P8_15 => MultiStep15;
		public ConfigItem P8_16 => MultiStep0Source;
		public ConfigItem P8_17 => MultiStep1Source;
		#endregion
		#region P9组 别名
		public ConfigItem P9_00 => PLCConfig;
		public ConfigItem P9_01 => PLCStep0Config;
		public ConfigItem P9_02 => PLCStep0Time;
		public ConfigItem P9_03 => PLCStep1Config;
		public ConfigItem P9_04 => PLCStep1Time;
		public ConfigItem P9_05 => PLCStep2Config;
		public ConfigItem P9_06 => PLCStep2Time;
		public ConfigItem P9_07 => PLCStep3Config;
		public ConfigItem P9_08 => PLCStep3Time;
		public ConfigItem P9_09 => PLCStep4Config;
		public ConfigItem P9_10 => PLCStep4Time;
		public ConfigItem P9_11 => PLCStep5Config;
		public ConfigItem P9_12 => PLCStep5Time;
		public ConfigItem P9_13 => PLCStep6Config;
		public ConfigItem P9_14 => PLCStep6Time;
		public ConfigItem P9_15 => PLCStep7Config;
		public ConfigItem P9_16 => PLCStep7Time;
		public ConfigItem P9_17 => PLCStep8Config;
		public ConfigItem P9_18 => PLCStep8Time;
		public ConfigItem P9_19 => PLCStep9Config;
		public ConfigItem P9_20 => PLCStep9Time;
		public ConfigItem P9_21 => PLCStep10Config;
		public ConfigItem P9_22 => PLCStep10Time;
		public ConfigItem P9_23 => PLCStep11Config;
		public ConfigItem P9_24 => PLCStep11Time;
		public ConfigItem P9_25 => PLCStep12Config;
		public ConfigItem P9_26 => PLCStep12Time;
		public ConfigItem P9_27 => PLCStep13Config;
		public ConfigItem P9_28 => PLCStep13Time;
		public ConfigItem P9_29 => PLCStep14Config;
		public ConfigItem P9_30 => PLCStep14Time;
		public ConfigItem P9_31 => PLCStep15Config;
		public ConfigItem P9_32 => PLCStep15Time;
		#endregion
		#region PA组 别名
		public ConfigItem PA_00 => PIDStrategy;
		public ConfigItem PA_01 => PIDSetpointSource;
		public ConfigItem PA_02 => PIDDigitalSetpoint;
		public ConfigItem PA_03 => PIDFeedbackSource;
		public ConfigItem PA_04 => PIDDirection;
		public ConfigItem PA_05 => PIDSampleTime;
		public ConfigItem PA_06 => PIDKp1;
		public ConfigItem PA_07 => PIDTi1;
		public ConfigItem PA_08 => PIDTd1;
		public ConfigItem PA_09 => PIDBiasLimit;
		public ConfigItem PA_10 => PIDDerivativeFilter;
		public ConfigItem PA_11 => PIDSetpointRamp;
		public ConfigItem PA_12 => PIDFeedbackFilter;
		public ConfigItem PA_13 => PIDOutputFilter;
		public ConfigItem PA_14 => PIDKp2;
		public ConfigItem PA_15 => PIDTi2;
		public ConfigItem PA_16 => PIDTd2;
		public ConfigItem PA_17 => PIDParamSwitch;
		public ConfigItem PA_18 => PIDSwitchBias1;
		public ConfigItem PA_19 => PIDSwitchBias2;
		public ConfigItem PA_20 => PIDInitialValue;
		public ConfigItem PA_21 => PIDInitialHold;
		public ConfigItem PA_22 => PIDIntegralMode;
		public ConfigItem PA_23 => PIDFeedbackLossValue;
		public ConfigItem PA_24 => PIDFeedbackLossTime;
		public ConfigItem PA_25 => PIDFeedbackHighValue;
		public ConfigItem PA_26 => PIDFeedbackHighTime;
		public ConfigItem PA_27 => PIDStopOperation;
		public ConfigItem PA_28 => PIDStabilityResponse;
		public ConfigItem PA_29 => PIDUpperLimit;
		public ConfigItem PA_30 => PIDLowerLimit;
		#endregion
		#region Pb组 别名
		public ConfigItem Pb_00 => SwingConfig;
		public ConfigItem Pb_01 => SwingAmplitude;
		public ConfigItem Pb_02 => SwingJump;
		public ConfigItem Pb_03 => SwingPeriod;
		public ConfigItem Pb_04 => SwingRiseFactor;
		public ConfigItem Pb_05 => LengthSet;
		public ConfigItem Pb_06 => LengthActual;
		public ConfigItem Pb_07 => PulsePerMeter;
		public ConfigItem Pb_08 => CountSet;
		public ConfigItem Pb_09 => CountPreset;
		#endregion
		#region PC组 别名
		public ConfigItem PC_00 => DeviceAddress;
		public ConfigItem PC_01 => CommConfig;
		public ConfigItem PC_02 => CommTimeout;
		public ConfigItem PC_03 => SlaveResponseDelay;
		public ConfigItem PC_04 => MasterSlaveMode;
		public ConfigItem PC_05 => MasterOperation;
		public ConfigItem PC_06 => MasterCommPeriod;
		public ConfigItem PC_07 => SlaveReceiveFactor;
		#endregion
		#region Pd组 别名
		public ConfigItem Pd_00 => MFKeyFunction;
		public ConfigItem Pd_01 => StopResetFunction;
		public ConfigItem Pd_02 => StopDisplaySelect;
		public ConfigItem Pd_03 => RunDisplaySelect;
		public ConfigItem Pd_04 => CustomDisplayGroup;
		public ConfigItem Pd_05 => CustomDisplay1;
		public ConfigItem Pd_06 => CustomDisplay2;
		public ConfigItem Pd_07 => CustomDisplay3;
		public ConfigItem Pd_08 => CustomDisplay4;
		public ConfigItem Pd_09 => CopyAction;
		public ConfigItem Pd_10 => UserPassword;
		#endregion
		#region PE组 别名
		public ConfigItem PE_00 => EnergyBrakeEnable;
		public ConfigItem PE_01 => EnergyBrakeVoltage;
		public ConfigItem PE_02 => BrakeDutyStatistic;
		public ConfigItem PE_03 => OverVoltageStallSelect;
		public ConfigItem PE_04 => OverVoltageStallPoint;
		public ConfigItem PE_05 => PowerLossStallEnable;
		public ConfigItem PE_06 => PowerLossStallVoltage;
		public ConfigItem PE_07 => PowerLossRecoverTime;
		public ConfigItem PE_08 => PowerLossStallStrength;
		public ConfigItem PE_09 => UnderVoltageFreqLimitEnable;
		public ConfigItem PE_10 => BusUnderVoltagePoint;
		public ConfigItem PE_11 => BusOverVoltagePoint;
		#endregion
		#region PF组 别名
		public ConfigItem PF_00 => MotorOverloadWarnValue;
		public ConfigItem PF_01 => MotorOverloadWarnTime;
		public ConfigItem PF_02 => MotorOverloadWarnAction;
		public ConfigItem PF_03 => MotorOverloadTripValue;
		public ConfigItem PF_04 => MotorOverloadTripTime;
		public ConfigItem PF_05 => MotorTempChannel;
		public ConfigItem PF_06 => MotorOverTempTrip;
		public ConfigItem PF_07 => MotorOverTempWarnValue;
		public ConfigItem PF_08 => MotorOverTempWarnTime;
		public ConfigItem PF_09 => MotorOverTempWarnAction;
		public ConfigItem PF_10 => TorqueProtectUpper;
		public ConfigItem PF_11 => TorqueUpperDetectTime;
		public ConfigItem PF_12 => TorqueProtectLower;
		public ConfigItem PF_13 => TorqueLowerDetectTime;
		public ConfigItem PF_14 => TorqueProtectAction;
		public ConfigItem PF_15 => ModuleOverTempTrip;
		public ConfigItem PF_16 => ModuleOverTempWarnValue;
		public ConfigItem PF_17 => TempSensorFailValue;
		public ConfigItem PF_18 => ModuleOverTempDetectTime;
		public ConfigItem PF_19 => ModuleOverTempWarnAction;
		public ConfigItem PF_20 => FanWorkMode;
		public ConfigItem PF_21 => FanStartTemp;
		public ConfigItem PF_22 => FanStopDelay;
		public ConfigItem PF_23 => InputPhaseLossProtect;
		public ConfigItem PF_24 => OutputPhaseLossProtect;
		public ConfigItem PF_25 => GroundShortProtect;
		public ConfigItem PF_26 => FaultAutoResetCount;
		public ConfigItem PF_27 => FaultAutoResetInterval;
		public ConfigItem PF_28 => FaultAutoResetConfig;
		#endregion
		#region A0组 别名
		public ConfigItem A0_00 => PowerOnTerminalProtect;
		public ConfigItem A0_01 => SleepFrequency;
		public ConfigItem A0_02 => SleepDelay;
		public ConfigItem A0_03 => WakeFrequency;
		public ConfigItem A0_04 => WakeDelay;
		public ConfigItem A0_05 => TimerUnit;
		public ConfigItem A0_06 => RunTimerSetting;
		public ConfigItem A0_07 => ZeroCurrentWidth;
		public ConfigItem A0_08 => ZeroCurrentDelay;
		public ConfigItem A0_09 => CurrentLimitDetect;
		public ConfigItem A0_10 => CurrentLimitDelay;
		public ConfigItem A0_11 => AnyCurrentDetect1;
		public ConfigItem A0_12 => AnyCurrentWidth1;
		public ConfigItem A0_13 => AnyCurrentDetect2;
		public ConfigItem A0_14 => AnyCurrentWidth2;
		public ConfigItem A0_15 => TargetFreqArrival;
		public ConfigItem A0_16 => FDT1Value;
		public ConfigItem A0_17 => FDT1Width;
		public ConfigItem A0_18 => FDT2Value;
		public ConfigItem A0_19 => FDT2Width;
		public ConfigItem A0_20 => AnyFreqDetect1;
		public ConfigItem A0_21 => AnyFreqWidth1;
		public ConfigItem A0_22 => AnyFreqDetect2;
		public ConfigItem A0_23 => AnyFreqWidth2;
		public ConfigItem A0_24 => AIDetectConfig;
		public ConfigItem A0_25 => AIOverLimitValue;
		public ConfigItem A0_26 => AILossValue;
		public ConfigItem A0_27 => AIInputAccuracy;
		public ConfigItem A0_28 => MultiStepMode;
		public ConfigItem A0_29 => EnergyCalibCoeff;
		public ConfigItem A0_30 => EnergyPrice;
		public ConfigItem A0_31 => EnergyCostLow;
		public ConfigItem A0_32 => EnergyCostHigh;
		public ConfigItem A0_33 => MotorSwitchTime;
		public ConfigItem A0_34 => CommFreqMode;
		#endregion
		#region A1组 别名
		public ConfigItem A1_00 => AI1CurvePoint0Value;
		public ConfigItem A1_01 => AI1CurvePoint0Setting;
		public ConfigItem A1_02 => AI1CurvePoint1Value;
		public ConfigItem A1_03 => AI1CurvePoint1Setting;
		public ConfigItem A1_04 => AI1CurvePoint2Value;
		public ConfigItem A1_05 => AI1CurvePoint2Setting;
		public ConfigItem A1_06 => AI1CurvePoint3Value;
		public ConfigItem A1_07 => AI1CurvePoint3Setting;
		public ConfigItem A1_08 => AI2CurvePoint0Value;
		public ConfigItem A1_09 => AI2CurvePoint0Setting;
		public ConfigItem A1_10 => AI2CurvePoint1Value;
		public ConfigItem A1_11 => AI2CurvePoint1Setting;
		public ConfigItem A1_12 => AI2CurvePoint2Value;
		public ConfigItem A1_13 => AI2CurvePoint2Setting;
		public ConfigItem A1_14 => AI2CurvePoint3Value;
		public ConfigItem A1_15 => AI2CurvePoint3Setting;
		#endregion
		#region A2组 别名
		public ConfigItem A2_00 => VirtualVDI1Func;
		public ConfigItem A2_01 => VirtualVDI2Func;
		public ConfigItem A2_02 => VirtualVDI3Func;
		public ConfigItem A2_03 => VirtualVDI4Func;
		public ConfigItem A2_04 => VirtualVDILink;
		public ConfigItem A2_05 => VirtualVDIState;
		public ConfigItem A2_06 => VirtualVDO1Func;
		public ConfigItem A2_07 => VirtualVDO2Func;
		public ConfigItem A2_08 => VirtualVDO3Func;
		public ConfigItem A2_09 => VirtualVDO4Func;
		public ConfigItem A2_10 => VirtualVDO1Delay;
		public ConfigItem A2_11 => VirtualVDO2Delay;
		public ConfigItem A2_12 => VirtualVDO3Delay;
		public ConfigItem A2_13 => VirtualVDO4Delay;
		public ConfigItem A2_14 => VirtualVDOActiveLevel;
		#endregion
		#region A3组 别名
		public ConfigItem A3_00 => AddressMappingEnable;
		public ConfigItem A3_01 => ParamOriginalAddr1;
		public ConfigItem A3_02 => ParamMappedAddr1;
		public ConfigItem A3_03 => ParamOriginalAddr2;
		public ConfigItem A3_04 => ParamMappedAddr2;
		public ConfigItem A3_05 => ParamOriginalAddr3;
		public ConfigItem A3_06 => ParamMappedAddr3;
		public ConfigItem A3_07 => ParamOriginalAddr4;
		public ConfigItem A3_08 => ParamMappedAddr4;
		public ConfigItem A3_09 => ParamOriginalAddr5;
		public ConfigItem A3_10 => ParamMappedAddr5;
		public ConfigItem A3_11 => ParamOriginalAddr6;
		public ConfigItem A3_12 => ParamMappedAddr6;
		public ConfigItem A3_13 => ParamOriginalAddr7;
		public ConfigItem A3_14 => ParamMappedAddr7;
		public ConfigItem A3_15 => ParamOriginalAddr8;
		public ConfigItem A3_16 => ParamMappedAddr8;
		#endregion
		#region A4组 别名
		public ConfigItem A4_00 => CommonParamAutoRecord;
		public ConfigItem A4_01 => CommonParam1;
		public ConfigItem A4_02 => CommonParam2;
		public ConfigItem A4_03 => CommonParam3;
		public ConfigItem A4_04 => CommonParam4;
		public ConfigItem A4_05 => CommonParam5;
		public ConfigItem A4_06 => CommonParam6;
		public ConfigItem A4_07 => CommonParam7;
		public ConfigItem A4_08 => CommonParam8;
		public ConfigItem A4_09 => CommonParam9;
		public ConfigItem A4_10 => CommonParam10;
		public ConfigItem A4_11 => CommonParam11;
		public ConfigItem A4_12 => CommonParam12;
		public ConfigItem A4_13 => CommonParam13;
		public ConfigItem A4_14 => CommonParam14;
		public ConfigItem A4_15 => CommonParam15;
		public ConfigItem A4_16 => CommonParam16;
		public ConfigItem A4_17 => CommonParam17;
		public ConfigItem A4_18 => CommonParam18;
		public ConfigItem A4_19 => CommonParam19;
		public ConfigItem A4_20 => CommonParam20;
		#endregion
		#region U0组 别名
		public ConfigItem U0_00 => RunFrequency;
		public ConfigItem U0_01 => SetFrequency;
		public ConfigItem U0_02 => BusVoltage;
		public ConfigItem U0_03 => OutputVoltage;
		public ConfigItem U0_04 => OutputCurrent;
		public ConfigItem U0_05 => OutputFrequency;
		public ConfigItem U0_06 => SetTorque;
		public ConfigItem U0_07 => OutputTorque;
		public ConfigItem U0_08 => OutputPower;
		public ConfigItem U0_09 => MotorSpeed;
		public ConfigItem U0_10 => HeatsinkTemp;
		public ConfigItem U0_11 => MotorTemp;
		public ConfigItem U0_12 => RunStatus;
		public ConfigItem U0_13 => AI1Voltage;
		public ConfigItem U0_14 => AI2Voltage;
		public ConfigItem U0_15 => InputTerminalStatus;
		public ConfigItem U0_16 => OutputTerminalStatus;
		public ConfigItem U0_17 => PulseInputPFI;
		public ConfigItem U0_18 => AO1Output;
		public ConfigItem U0_19 => PulseOutputPFO;
		public ConfigItem U0_20 => VirtualVDIStatus;
		public ConfigItem U0_21 => VirtualVDOStatus;
		public ConfigItem U0_22 => RunTimeHours;
		public ConfigItem U0_23 => RunTimeMinutes;
		public ConfigItem U0_24 => PIDSet;
		public ConfigItem U0_25 => PIDFeedback;
		public ConfigItem U0_26 => CounterValue;
		public ConfigItem U0_27 => LengthValue;
		public ConfigItem U0_28 => PowerOnTimeLow;
		public ConfigItem U0_29 => PowerOnTimeHigh;
		public ConfigItem U0_30 => VFSeparatedTargetVoltage;
		public ConfigItem U0_31 => VFSeparatedOutputVoltage;
		public ConfigItem U0_32 => PLCStage;
		public ConfigItem U0_33 => PLCTime;
		public ConfigItem U0_34 => EnergyLow;
		public ConfigItem U0_35 => EnergyHigh;
		public ConfigItem U0_36 => UpDnBias;
		public ConfigItem U0_37 => SystemWord;
		#endregion
		#region U1组 别名
		public ConfigItem U1_00 => CurrentFaultIndex;
		public ConfigItem U1_01 => Fault1Index;
		public ConfigItem U1_02 => Fault1RunFreq;
		public ConfigItem U1_03 => Fault1OutFreq;
		public ConfigItem U1_04 => Fault1OutCurrent;
		public ConfigItem U1_05 => Fault1BusVoltH;
		public ConfigItem U1_06 => Fault1BusVoltL;
		public ConfigItem U1_07 => Fault1BusVolt;
		public ConfigItem U1_08 => Fault1ModuleTemp;
		public ConfigItem U1_09 => Fault1InputStatus;
		public ConfigItem U1_10 => Fault1RunHours;
		public ConfigItem U1_11 => Fault2Index;
		public ConfigItem U1_12 => Fault2RunFreq;
		public ConfigItem U1_13 => Fault2OutFreq;
		public ConfigItem U1_14 => Fault2OutCurrent;
		public ConfigItem U1_15 => Fault2BusVoltH;
		public ConfigItem U1_16 => Fault2BusVoltL;
		public ConfigItem U1_17 => Fault2BusVolt;
		public ConfigItem U1_18 => Fault2ModuleTemp;
		public ConfigItem U1_19 => Fault2InputStatus;
		public ConfigItem U1_20 => Fault2RunHours;
		public ConfigItem U1_21 => Fault3Index;
		public ConfigItem U1_22 => Fault3RunFreq;
		public ConfigItem U1_23 => Fault3OutFreq;
		public ConfigItem U1_24 => Fault3OutCurrent;
		public ConfigItem U1_25 => Fault3BusVoltH;
		public ConfigItem U1_26 => Fault3BusVoltL;
		public ConfigItem U1_27 => Fault3BusVolt;
		public ConfigItem U1_28 => Fault3ModuleTemp;
		public ConfigItem U1_29 => Fault3InputStatus;
		public ConfigItem U1_30 => Fault3RunHours;
		public ConfigItem U1_31 => Fault4Index;
		public ConfigItem U1_32 => Fault5Index;
		public ConfigItem U1_33 => Fault6Index;
		public ConfigItem U1_34 => Fault7Index;
		public ConfigItem U1_35 => Fault8Index;
		public ConfigItem U1_36 => Fault9Index;
		public ConfigItem U1_37 => Fault10Index;
		#endregion
		#region n1组 别名
		public ConfigItem n1_00 => DealerPassword;
		public ConfigItem n1_01 => DealerRunTimeSetting;
		public ConfigItem n1_02 => DealerCommand;
		#endregion
    }
}
